=== cristianonovelli/tebes3/trunk/TeBES/ejb/TeBES_Artifacts/xmlschemas/TAML/testAssertionMarkupLanguage.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
     Test Assertions Part 2 - Test Assertion Markup Language Version 1.0
     Committee Specification 02
     30 November 2011
     Copyright (c) OASIS Open 2011. All Rights Reserved.
     Source: http://docs.oasis-open.org/tag/taml/v1.0/cs02/xsd/
-->
<!-- 
   Test Assertion Markup Language
   Version: 1.0 
   OASIS Open Test Assertion Guidelines TC
   Date: May 2011
   Editor: Stephen D. Green
   
   Copyright © OASIS Open 2008-2011. All Rights Reserved.
   
   All capitalized terms in the following text have the meanings assigned to them
   in the OASIS Intellectual Property Rights Policy (the "OASIS IPR Policy"). The
   full Policy may be found at the OASIS website.
   
   This document and translations of it may be copied and furnished to others, and
   derivative works that comment on or otherwise explain it or assist in its
   implementation may be prepared, copied, published, and distributed, in whole or
   in part, without restriction of any kind, provided that the above copyright
   notice and this section are included on all such copies and derivative works.
   However, this document itself may not be modified in any way, including by
   removing the copyright notice or references to OASIS, except as needed for the
   purpose of developing any document or deliverable produced by an OASIS
   Technical Committee (in which case the rules applicable to copyrights, as set
   forth in the OASIS IPR Policy, must be followed) or as required to translate it
   into languages other than English.
   
   The limited permissions granted above are perpetual and will not be revoked by
   OASIS or its successors or assigns.
   
   This document and the information contained herein is provided on an "AS IS"
   basis and OASIS DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT
   LIMITED TO ANY WARRANTY THAT THE USE OF THE INFORMATION HEREIN WILL NOT
   INFRINGE ANY OWNERSHIP RIGHTS OR ANY IMPLIED WARRANTIES OF MERCHANTABILITY OR
   FITNESS FOR A PARTICULAR PURPOSE. 
  -->
<xs:schema xmlns="http://docs.oasis-open.org/ns/tag/taml-201002/"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://docs.oasis-open.org/ns/tag/taml-201002/" elementFormDefault="qualified"
  attributeFormDefault="unqualified" version="1.0">

  <xs:element name="testAssertion" type="testAssertion_type"/>
  <xs:element name="testAssertionSet" type="testAssertionSet_type"/>

  <xs:simpleType name="codeExtension_type">
    <xs:restriction base="xs:QName">
      <xs:pattern value="[\c-[:]]+:[\c-[:]]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="comment_type" mixed="true">
    <xs:sequence>
      <xs:any maxOccurs="unbounded" minOccurs="0" namespace="##any" processContents="skip"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="common_type" mixed="true">
    <xs:sequence>
      <xs:any maxOccurs="unbounded" minOccurs="0" namespace="##any" processContents="skip"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="description_type" mixed="true">
    <xs:sequence>
      <xs:any maxOccurs="unbounded" minOccurs="0" namespace="##any" processContents="skip"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="interpretation_type">
    <xs:simpleContent>
      <xs:extension base="xs:normalizedString">
        <xs:anyAttribute namespace="##other" processContents="skip"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="normativeSource_type" mixed="true">
    <xs:sequence>
      <xs:element name="comment" type="comment_type" minOccurs="0"/>
      <xs:element name="interpretation" type="interpretation_type" minOccurs="0"/>
      <xs:element name="refSourceItem" type="refSourceItem_type" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="textSourceItem" type="textSourceItem_type" minOccurs="0"
        maxOccurs="unbounded"/>
      <xs:element name="derivedSourceItem" type="refSourceItem_type" minOccurs="0"
        maxOccurs="unbounded"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="predicate_type" mixed="true">
    <xs:sequence>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="lg" type="xs:normalizedString"/>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="prerequisite_type" mixed="true">
    <xs:sequence>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="lg" type="xs:normalizedString"/>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="prescription_type">
    <xs:simpleContent>
      <xs:extension base="xs:normalizedString">
        <xs:attribute name="level" type="prescriptionLevelCode_type"/>
        <xs:anyAttribute namespace="##other" processContents="skip"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="prescriptionLevelCode_type">
    <xs:union memberTypes="prescriptionLevelBaseCode_type codeExtension_type"/>
  </xs:simpleType>

  <xs:simpleType name="prescriptionLevelBaseCode_type">
    <xs:restriction base="xs:normalizedString">
      <xs:enumeration value="mandatory"/>
      <xs:enumeration value="permitted"/>
      <xs:enumeration value="preferred"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="refSourceItem_type">
    <xs:simpleContent>
      <xs:extension base="xs:normalizedString">
        <xs:attributeGroup ref="resource_attributeGroup"/>
        <xs:anyAttribute namespace="##other" processContents="skip"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="report_type" mixed="true">
    <xs:sequence>
      <xs:any namespace="##any" processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="lg" type="xs:normalizedString"/>
    <xs:attribute name="label" type="xs:normalizedString"/>
    <xs:attribute name="message" type="xs:normalizedString"/>
    <xs:attribute name="when" type="xs:normalizedString"/>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:attributeGroup name="resource_attributeGroup">
    <xs:attribute name="srcname" type="xs:normalizedString"/>
    <xs:attribute name="uri" type="xs:anyURI"/>
    <xs:attribute name="documentId" type="xs:normalizedString"/>
    <xs:attribute name="versionId" type="xs:normalizedString"/>
    <xs:attribute name="revisionId" type="xs:normalizedString"/>
    <xs:attribute name="resourceProvenanceId" type="xs:normalizedString"/>
  </xs:attributeGroup>

  <xs:complexType name="tag_type">
    <xs:simpleContent>
      <xs:extension base="xs:normalizedString">
        <xs:attribute name="tname" type="xs:normalizedString" use="required"/>
        <xs:anyAttribute namespace="##other" processContents="skip"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="target_type" mixed="true">
    <xs:sequence>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="type" type="xs:normalizedString"/>
    <xs:attribute name="lg" type="xs:normalizedString"/>
    <xs:attribute name="idscheme" type="xs:normalizedString"/>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="testAssertion_type">
    <xs:sequence>
      <xs:element name="description" type="description_type" minOccurs="0"/>
      <xs:element name="normativeSource" type="normativeSource_type" minOccurs="0"/>
      <xs:element name="var" type="var_type" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="target" type="target_type" minOccurs="0"/>
      <xs:element name="prerequisite" type="prerequisite_type" minOccurs="0"/>
      <xs:element name="predicate" type="predicate_type" minOccurs="0"/>
      <xs:element name="prescription" type="prescription_type" minOccurs="0"/>
      <xs:element name="report" type="report_type" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="tag" type="tag_type" minOccurs="0" maxOccurs="unbounded"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:normalizedString" use="required"/>
    <xs:attribute name="lg" type="xs:normalizedString"/>
    <xs:attribute name="name" type="xs:normalizedString"/>
    <xs:attribute name="schemaVersionId" type="xs:normalizedString"/>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="testAssertionRefList_type">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="testAssertionRef"
        type="testAssertionRef_type"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="sourcedoc" type="xs:anyURI"/>
    <xs:attribute name="listname" type="xs:normalizedString"/>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="testAssertionRef_type">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="taid" type="xs:normalizedString"/>
        <xs:attribute name="name" type="xs:normalizedString"/>
        <xs:attribute name="sourcedoc" type="xs:anyURI"/>
        <xs:anyAttribute namespace="##other" processContents="skip"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="testAssertionSet_type">
    <xs:sequence>
      <xs:element minOccurs="0" name="common" type="common_type"/>
      <xs:element name="testAssertionRefList" type="testAssertionRefList_type" minOccurs="0"
        maxOccurs="unbounded"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="testAssertion" type="testAssertion_type"/>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="setid" type="xs:normalizedString"/>
    <xs:attribute name="setname" type="xs:normalizedString"/>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="textSourceItem_type">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="extension" type="xs:boolean"/>
        <xs:attribute name="txtname" type="xs:normalizedString"/>
        <xs:anyAttribute namespace="##other" processContents="skip"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="var_type" mixed="true">
    <xs:sequence>
      <xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="lg" type="xs:normalizedString"/>
    <xs:attribute name="vname" type="xs:normalizedString" use="required"/>
    <xs:attribute name="vtype" type="xs:normalizedString"/>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

</xs:schema>

=== cristianonovelli/tebes3/trunk/TeBES/ejb/TeBES_Artifacts/testsuites/UBL/TS-004_itnat/TC-001_ITNAT-UBL-T10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    Created by Cristiano Novelli 
    ENEA, Bologna, 2012-25-05   
    Version=0.1
    
    Notes:
    - The tebes namespace is defined to extend TAML with new elements or attributes used in the TeBES platform
-->

<taml:testAssertionSet 
    xmlns:taml="http://docs.oasis-open.org/ns/tag/taml-201002/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://docs.oasis-open.org/ns/tag/taml-201002/ http://docs.oasis-open.org/tag/taml/v1.0/cs02/xsd/testAssertionMarkupLanguage.xsd"
    xmlns:tebes="http://www.ubl-italia.org/TeBES"
    setid="TC-001_TS-004"
    setname="Test Case for UBL Invoice Italian PEPPOL Schematron validation"
	tebes:version="0.1">
    
    <taml:testAssertionRefList listname="prerequisites"> 
        <!-- 
            The taml:testAssertionRef attributes have to take the following values:
            - @taid: testAssertion/@id of the test assertion;
            - @name: testAssertion/@name of the test assertion;
            - @tebes:version: version of this Test Suite specification for TeBES
        -->        
        <taml:testAssertionRef 
            taid="TA-001_TC-001_TS-003" 
            name="EUGEN-UBL-T10" 
            sourcedoc="http://www.ubl-italia.org/TeBES/testsuites/UBL/TS-003_eugen/TC-001_EUGEN-UBL-T10.xml" 
            tebes:version="0.1" />
    </taml:testAssertionRefList>	        	
    
    <taml:testAssertion 
        id="TA-001_TC-001_TS-004" 
        name="ITNAT-UBL-T10" 
        tebes:isNotePresent="false">

        <taml:description>
            Italian PEPPOL UBL Invoice Schematron Validation.
        </taml:description>
        
        <taml:normativeSource>
            <taml:comment></taml:comment>
            <taml:refSourceItem></taml:refSourceItem>
            <taml:textSourceItem></taml:textSourceItem>
        </taml:normativeSource>

        <taml:var vname="TA-001_TC-001_TS-003" vtype="http://docs.oasis-open.org/ns/tag/taml-201002/">taml:TA-001_TC-001_TS-003 eq 'pass'</taml:var>
        
        <taml:var vname="ITNAT-UBL-T10" vtype="http://purl.oclc.org/dsdl/schematron">http://www.ubl-italia.org/TeBES/schematrons/UBL-T10/itnat/schematron/UBL/ITNAT-UBL-T10.sch</taml:var>

        <taml:target type="xml">document</taml:target>
 
        <taml:prerequisite>TA-001_TC-001_TS-003</taml:prerequisite>        
        
        <taml:predicate>ITNAT-UBL-T10</taml:predicate>
        
        <taml:prescription level="mandatory" />
        
        <taml:report 
            label="pass" 
            message="OK Italian PEPPOL (ITNAT-UBL-T10) Schematron validation of UBL Invoice">
            The file is valid against Italian PEPPOL UBL2 Invoice Schematron.
        </taml:report>
        <taml:report 
            label="fail" 
            message="Failed Italian PEPPOL (ITNAT-UBL-T10) Schematron UBL Invoice validation">
            The file does not contain an UBL Invoice valid against BIICORE Schematron.
        </taml:report>
        <taml:report 
            label="notQualified" 
            message="Not qualified to perform the Italian PEPPOL (ITNAT-UBL-T10) Schematron UBL Invoice validation">
            The file is not valid against UBL Invoice XML Schema.
        </taml:report>
    </taml:testAssertion>           
    
</taml:testAssertionSet>

=== cristianonovelli/tebes3/trunk/TeBES/ejb/TeBES_Artifacts/testsuites/UBL/TS-003_eugen/TC-001_EUGEN-UBL-T10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    Created by Cristiano Novelli 
    ENEA, Bologna, 2012-25-05   
    Version=0.1
    
    Notes:
    - The tebes namespace is defined to extend TAML with new elements or attributes used in the TeBES platform
-->

<taml:testAssertionSet 
    xmlns:taml="http://docs.oasis-open.org/ns/tag/taml-201002/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://docs.oasis-open.org/ns/tag/taml-201002/ http://docs.oasis-open.org/tag/taml/v1.0/cs02/xsd/testAssertionMarkupLanguage.xsd"
    xmlns:tebes="http://www.ubl-italia.org/TeBES"
    setid="TC-001_TS-003"
    setname="Test Case for UBL Invoice European PEPPOL Schematron validation"
	tebes:version="0.1">
    
    <taml:testAssertionRefList listname="prerequisites">  
        <!-- 
            The taml:testAssertionRef attributes have to take the following values:
            - @taid: testAssertion/@id of the test assertion;
            - @name: testAssertion/@name of the test assertion;
            - @tebes:version: version of this Test Suite specification for TeBES
        -->
        <taml:testAssertionRef 
            taid="TA-001_TC-001_TS-002" 
            name="BIICORE-UBL-T10" 
            sourcedoc="http://www.ubl-italia.org/TeBES/testsuites/UBL/TS-002_bii/TC-001_BII-UBL-T10.xml" 
            tebes:version="0.1" />
        <taml:testAssertionRef 
            taid="TA-002_TC-001_TS-002" 
            name="BIIPROFILES-UBL-T10" 
            sourcedoc="http://www.ubl-italia.org/TeBES/testsuites/UBL/TS-002_bii/TC-001_BII-UBL-T10.xml" 
            tebes:version="0.1" />        
        <taml:testAssertionRef 
            taid="TA-003_TC-001_TS-002" 
            name="BIIRULES-UBL-T10" 
            sourcedoc="http://www.ubl-italia.org/TeBES/testsuites/UBL/TS-002_bii/TC-001_BII-UBL-T10.xml" 
            tebes:version="0.1" />    
    </taml:testAssertionRefList>	        	
    
    <taml:testAssertion 
        id="TA-001_TC-001_TS-003" 
        name="EUGEN-UBL-T10" 
        tebes:isNotePresent="false">

        <taml:description>
            European PEPPOL UBL Invoice Schematron Validation.
        </taml:description>
        
        <taml:normativeSource>
            <taml:comment></taml:comment>
            <taml:refSourceItem></taml:refSourceItem>
            <taml:textSourceItem></taml:textSourceItem>
        </taml:normativeSource>
        
        <taml:var vname="EUGEN-UBL-T10" vtype="http://purl.oclc.org/dsdl/schematron">http://winter.bologna.enea.it/peppol_schema_rep/schematron/eugen/UBL/EUGEN-UBL-T10.sch</taml:var>

        <taml:var vname="TA-001_TC-001_TS-002" vtype="http://docs.oasis-open.org/ns/tag/taml-201002/">taml:TA-001_TC-001_TS-002 eq 'pass'</taml:var>
        <taml:var vname="TA-002_TC-001_TS-002" vtype="http://docs.oasis-open.org/ns/tag/taml-201002/">taml:TA-002_TC-001_TS-002 eq 'pass'</taml:var>
        <taml:var vname="TA-003_TC-001_TS-002" vtype="http://docs.oasis-open.org/ns/tag/taml-201002/">taml:TA-003_TC-001_TS-002 eq 'pass'</taml:var>
        
        <taml:target lg="xml" type="document">document</taml:target>
        
        <!-- taml:prerequisite>TA-001_TC-001_TS-002 AND TA-002_TC-001_TS-002 AND TA-003_TC-001_TS-002</taml:prerequisite -->
        <taml:prerequisite>TA-003_TC-001_TS-002</taml:prerequisite>
        
        <taml:predicate>EUGEN-UBL-T10</taml:predicate>
        
        <taml:prescription level="mandatory" />
        
        <taml:report 
            label="pass" 
            message="OK European PEPPOL (EUGEN-UBL-T10) Schematron validation of UBL Invoice">
            The file is valid against European PEPPOL UBL2 Invoice Schematron.
        </taml:report>
        <taml:report 
            label="fail" 
            message="Failed European PEPPOL (EUGEN-UBL-T10) Schematron UBL Invoice validation">
            The file does not contain an UBL Invoice valid against BIICORE Schematron.
        </taml:report>
        <taml:report 
            label="notQualified" 
            message="Not qualified to perform the European PEPPOL (EUGEN-UBL-T10) Schematron UBL Invoice validation">
            The file is not valid against UBL Invoice XML Schema.
        </taml:report>
    </taml:testAssertion>

</taml:testAssertionSet>

=== cristianonovelli/tebes3/TeBES/ejb/TeBES_Artifacts/testsuites/MODAML_2013-1/TS-009_MML_BusinessDocBR/TC-001_TEXOrder-MML-BR.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../xsl/TeBES_TestSuite.xsl" ?>
<!-- 
    Created by Arianna Brutti
    ENEA, Bologna, 2012-25-05   
    Version=0.1
    
    Notes:
    - The tebes namespace is defined to extend TAML with new elements or attributes used in the TeBES platform
-->

<taml:testAssertionSet 
    xmlns:taml="http://docs.oasis-open.org/ns/tag/taml-201002/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://docs.oasis-open.org/ns/tag/taml-201002/ http://docs.oasis-open.org/tag/taml/v1.0/cs02/xsd/testAssertionMarkupLanguage.xsd"
    xmlns:tebes="http://www.ubl-italia.org/TeBES"
    setid="TC-001_TS-009"
    setname="Test Case for Textile Purchase Order Business Rules validation"
	tebes:version="0.1">
    
    <taml:testAssertionRefList listname="prerequisites">   
        <!-- 
            The taml:testAssertionRef attributes have to take the following values:
            - @taid: testAssertion/@id of the test assertion;
            - @name: testAssertion/@name of the test assertion;
            - @tebes:version: version of this Test Suite specification for TeBES
        -->
        <taml:testAssertionRef 
            taid="TA-001_TC-001_TS-008" 
            name="TEXOrder-MML" 
            sourcedoc="http://www.ubl-italia.org/TeBES/testsuites/MODAML_2013-1/TS-008_MML_BusinessDocStr/TC-001_TEXOrder-MML.xml" 
            tebes:version="0.1" />   
    </taml:testAssertionRefList>	        	
    
    <taml:testAssertion 
        id="TA-001_TC-001_TS-009" 
        name="TEXOrder-MML-BR" 
        tebes:isNotePresent="false">

        <taml:description>Business rules on Moda-ML Textile Purchase Order (applied through Schematron Validation).</taml:description>
        
        <taml:normativeSource>
            <taml:comment></taml:comment>
            <taml:refSourceItem></taml:refSourceItem>
            <taml:textSourceItem></taml:textSourceItem>
        </taml:normativeSource>

        <taml:var vname="TEXOrder-MML" vtype="http://docs.oasis-open.org/ns/tag/taml-201002/">taml:TA-001_TC-001_TS-008 eq 'pass'</taml:var>
        
        <taml:var vname="TEXOrder-MML-BR" vtype="http://purl.oclc.org/dsdl/schematron">http://www.moda-ml.net/moda-ml/repository/schematron/v2013-1/TEXOrderValidator.sch</taml:var>
        
        <!-- XML document, target of Test --> 
        <taml:target type="xml">document</taml:target>
        
        <taml:prerequisite>TEXOrder-MML</taml:prerequisite>
        
        <taml:predicate>TEXOrder-MML-BR</taml:predicate>
        
        <taml:prescription level="mandatory" />
        
        <taml:report 
            label="pass" 
            message="Moda-ML Textile Purchase Order Business Rules are satisfied.">The file is valid against Moda-ML Textile Purchase Order Business Rules.</taml:report>
        <taml:report 
            label="fail" 
            message="One or more Moda-ML Textile Purchase Order Business Rules are NOT satisfied.">The file is NOT valid against Moda-ML Textile Purchase Order Business Rules.</taml:report>
        <taml:report 
            label="notQualified" 
            message="Not qualified to perform the Moda-ML Textile Purchase Order Business Rules validation">The file is not qualified to perform the Moda-ML Textile Purchase Order Business Rules validation.</taml:report>
    </taml:testAssertion>
	
</taml:testAssertionSet>

=== cristianonovelli/tebes3/trunk/TeBES/ejb/TeBES_Artifacts/testsuites/UBL/TS-005_sdi/TC-001_SDI-UBL-T10.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../xsl/TeBES_TestSuite.xsl" ?>
<!-- 
    Created by Cristiano Novelli 
    ENEA, Bologna, 2012-25-05   
    Version=0.1
    
    Notes:
    - The tebes namespace is defined to extend TAML with new elements or attributes used in the TeBES platform
-->

<taml:testAssertionSet 
    xmlns:taml="http://docs.oasis-open.org/ns/tag/taml-201002/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://docs.oasis-open.org/ns/tag/taml-201002/ http://docs.oasis-open.org/tag/taml/v1.0/cs02/xsd/testAssertionMarkupLanguage.xsd"
    xmlns:tebes="http://www.ubl-italia.org/TeBES"
    setid="TC-001_TS-005"
    setname="Test Case for UBL Invoice Italian INTERCENT-ER Schematron validation"
	tebes:version="0.1">
    
    <taml:testAssertionRefList listname="prerequisites"> 
        
        <!-- 
            The taml:testAssertionRef attributes have to take the following values:
            - @taid: testAssertion/@id of the test assertion;
            - @name: testAssertion/@name of the test assertion;
            - @tebes:version: version of this Test Suite specification for TeBES
        -->        
        <taml:testAssertionRef 
            taid="TA-001_TC-001_TS-004" 
            name="ITNAT-UBL-T10" 
            sourcedoc="http://winter.bologna.enea.it/tebes-artifacts/testsuites/UBL/TS-004_itnat/TC-001_ITNAT-UBL-T10.xml" 
            tebes:version="0.1" />
    </taml:testAssertionRefList>	        	
    
    <taml:testAssertion 
        id="TA-001_TC-001_TS-005" 
        name="SDI-UBL" 
        tebes:isNotePresent="false">

        <taml:description>Italian INTERCENT-ER UBL Invoice Schematron Validation.</taml:description>
        
        <taml:normativeSource>
            <taml:comment></taml:comment>
            <taml:refSourceItem></taml:refSourceItem>
            <taml:textSourceItem></taml:textSourceItem>
        </taml:normativeSource>

        <taml:var vname="TA-001_TC-001_TS-004" vtype="http://docs.oasis-open.org/ns/tag/taml-201002/">taml:TA-001_TC-001_TS-004 eq 'pass'</taml:var>

        <taml:var vname="SDI-UBL" vtype="http://purl.oclc.org/dsdl/schematron">http://winter.bologna.enea.it/peppol_schema_rep/schematron/sdi/SDI-UBL-T10.sch</taml:var>

        <taml:target type="document" lg="xml">document</taml:target>
  
        <taml:prerequisite>TA-001_TC-001_TS-004</taml:prerequisite>

        <taml:predicate>SDI-UBL</taml:predicate>
        
        <taml:prescription level="mandatory" />
        
        <taml:report 
            label="pass" 
            message="OK Italian Intercent-ER (SDI-UBL) Schematron validation of UBL Invoice">The file is valid against Italian Intercent-ER (SDI-UBL) UBL2 Invoice Schematron.</taml:report>
        <taml:report 
            label="fail" 
            message="Failed Italian Intercent-ER (SDI-UBL) Schematron UBL Invoice validation">Failed Italian Intercent-ER (SDI-UBL) Schematron UBL Invoice validation.</taml:report>
        <taml:report 
            label="notQualified" 
            message="Not qualified to perform the Italian Intercent-ER (SDI-UBL) Schematron UBL Invoice validation">The file is not qualified to perform the Italian Intercent-ER (SDI-UBL) Schematron UBL Invoice validation.</taml:report>
    </taml:testAssertion>	             
    
</taml:testAssertionSet>

=== cristianonovelli/tebes3/TeBES/ejb/TeBES_Artifacts/testsuites/MODAML_2013-1/TS-008_MML_BusinessDocStr/TC-001_TEXOrder-MML.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../../../xsl/TeBES_TestSuite.xsl" ?>
<!-- 
	Created by Arianna Brutti
	ENEA, Bologna, 2015-17-02   
	Version=0.1
-->

<taml:testAssertionSet 
    xmlns:taml="http://docs.oasis-open.org/ns/tag/taml-201002/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://docs.oasis-open.org/ns/tag/taml-201002/ http://docs.oasis-open.org/tag/taml/v1.0/cs02/xsd/testAssertionMarkupLanguage.xsd"
	xmlns:tebes="http://www.ubl-italia.org/tebes"
    setid="TC-001_TS-008"
    setname="Test Case for MODA-ML Textile Purchase Order XML Schema validation."
	tebes:version="0.1">

    <taml:common>
        <taml:namespaces 
            xmlns:ml="http://www.moda-ml.org/moda-ml/repository/schema/v2013-1/TEXOrder.xsd" />
    </taml:common>
    
    
    <taml:testAssertion 
        id="TA-001_TC-001_TS-008" 
        name="TEXOrder-MML" 
        tebes:isNotePresent="false">

        <taml:description>MODA-ML Textile Purchase Order XML Schema validation.</taml:description>
        
        <taml:normativeSource>
            <taml:comment>Reference page of the MODA-ML document with Guide and Schema.</taml:comment>
            <taml:refSourceItem></taml:refSourceItem>
            <taml:textSourceItem></taml:textSourceItem>
        </taml:normativeSource>

        <taml:var vname="TEXOrder-MML" vtype="http://www.w3.org/TR/xpath20/">count(//ml:TEXOrder) ge 1</taml:var>
        
        <taml:target type="document" lg="xml">document</taml:target>
        
        <!-- 
            The XPath expression executes the XML Schema validation 
            on the XML root Invoice, calling the XML Schema specified by soap: namespace defined in taml:common.
            The "ge" XPath means "greater than or equal to". 
        -->
        <taml:predicate>TEXOrder-MML</taml:predicate>
        
        <taml:prescription level="mandatory" />
        
        <taml:report 
            label="pass" 
            message="OK validation document Textile Purchase Order against MODA-ML XML Schema.">OK validation document Textile Purchase Order against MODA-ML XML Schema.</taml:report>
        <taml:report 
            label="fail" 
            when="count(//ml:TEXOrder) ge 0"
            message="The document is NOT valid against MODA-ML Textile Purchase Order XML Schema.">The document is NOT valid against MODA-ML Textile Purchase Order XML Schema.</taml:report>

    </taml:testAssertion>
	
</taml:testAssertionSet>
